NAME : UNIBHA NEUPANE GROUP:L5CG11

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [9]:
#1
data = pd.read_csv("/content/drive/MyDrive/student.csv")
print("Top 5 rows:")
display(data.head())
print("Bottom 5 rows:")
display(data.tail())
print("\nDataset Info:")
data.info()
print("\nDataset Description:")
display(data.describe())
X = data[['Math', 'Reading']].values
Y = data['Writing'].values

Top 5 rows:

   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

Bottom 5 rows:

     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB

Dataset Description:

              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [11]:
#2
X = data[['Math', 'Reading']].values
print("Shape of X:", X.shape)
Y = data['Writing'].values
print("Shape of Y:", Y.shape)
W = np.zeros(X.shape[1])
print("Initial Weights W:", W)
print("Shape of W:", W.shape)

Shape of X: (1000, 2)
Shape of Y: (1000,)
Initial Weights W: [0. 0.]
Shape of W: (2,)

In [14]:
#3
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 800
Testing samples: 200

In [16]:
#4
def cost_function(X, Y, W):
    n = len(Y)
    Y_pred = np.dot(X, W)
    cost = (1 / (2 * n)) * np.sum((Y_pred - Y) ** 2)
    return cost

In [18]:
#5
X_test_case = np.array([[1, 2], [3, 4], [5, 6]])
Y_test_case = np.array([3, 7, 11])
W_test_case = np.array([1, 1])
cost = cost_function(X_test_case, Y_test_case, W_test_case)
if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong")

print("Cost function output:", cost)

Proceed Further
Cost function output: 0.0

In [21]:
#6
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = []
    m = len(Y)

    for i in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1 / m) * np.dot(X.T, loss)
        W = W - alpha * dw
        cost = cost_function(X, Y, W)
        cost_history.append(cost)

    return W, cost_history

In [23]:
#7
np.random.seed(0)
X_rand = np.random.rand(100, 3)
Y_rand = np.random.rand(100)
W_rand = np.random.rand(3)
alpha = 0.01
iterations = 1000

final_params, cost_history = gradient_descent(
    X_rand, Y_rand, W_rand, alpha, iterations
)

print("Final Parameters:", final_params)
print("Final Cost:", cost_history[-1])

Final Parameters: [0.20551667 0.54295081 0.10388027]
Final Cost: 0.05435492255484332

In [25]:
#8
def rmse(Y, Y_pred):
    error = Y - Y_pred
    rmse = np.sqrt(np.mean(error ** 2))
    return rmse

In [28]:
#9
def r2(Y, Y_pred):
    mean_y = np.mean(Y)
    ss_tot = np.sum((Y - mean_y) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    r2 = 1 - (ss_res / ss_tot)
    return r2

In [32]:
#10
def main():
    data = pd.read_csv("/content/drive/MyDrive/student.csv")
    X = data[['Math', 'Reading']].values
    Y = data['Writing'].values
    X_train, X_test, Y_train, Y_test = train_test_split(
        X, Y, test_size=0.2, random_state=42
    )

    W = np.zeros(X_train.shape[1])
    alpha = 0.00001
    iterations = 1000

    W_optimal, cost_history = gradient_descent(
        X_train, Y_train, W, alpha, iterations
    )

    Y_pred = np.dot(X_test, W_optimal)

    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)
    print("Final Weights:", W_optimal)
    print("Cost History (First 10):", cost_history[:10])
    print("RMSE:", model_rmse)
    print("R² Score:", model_r2)

main()

Final Weights: [0.34811659 0.64614558]
Cost History (First 10): [np.float64(2013.165570783755), np.float64(1640.286832599692), np.float64(1337.0619994901588), np.float64(1090.4794892850578), np.float64(889.9583270083234), np.float64(726.8940993009545), np.float64(594.2897260808594), np.float64(486.4552052951635), np.float64(398.7634463599484), np.float64(327.4517147324688)]
RMSE: 5.2798239764188635
R² Score: 0.8886354462786421

# 11
The linear regression model shows acceptable performance. Since the model is simple and uses only two features, it does not overfit the data. The prediction error is reasonable, and the R² value is positive, which indicates that the model is able to learn the relationship between Math, Reading, and Writing scores.

When experimenting with different learning rates, it was observed that a very small learning rate makes the training process very slow. A very large learning rate causes the cost function to become unstable. A moderate learning rate provides stable convergence and better learning performance.